### ISSUE TITLE
Keep sudo alive for the entire initial install

### ISSUE THREAD

**Issue by ezzatron** [jmalloc/dotfiles#11]
Thought I'd get you in on solving this one. I have a similar issue over at ezzatron/dotfiles#11. You mentioned you had a solution for this, but I couldn't find anything with a code search.

I came across https://gist.github.com/cowboy/3118588 after seeing a similar approach in mathiasbynens' dotfiles. It's basically this:

```bash
sudo -v
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
```

For such a small amount of code, this seems to work pretty well, but in the comments on that gist, I saw this comment thread:

> > Awesome... That's exactly what I'm looking for. Unfortunately it does not work with a long running task like a massive brew install. After that, the sudo session is expired and you have to re-enter a password for the next sudo command. Do you have any hints/experiences on that?!
>
> Homebrew explicitly invalidates the sudo timestamp, so AFAIK there's no way for this to work with brew.

So I suspect on initial installs, it probably won't work. Another person said this:

> I recently changed my dotfiles to use the sledge-hammer approach to sudoing by adding myself to /etc/sudoers for the duration of the script, because anything else just wouldn't work reliably.

So I'm wondering if a combination of:
1. Setting up passwordless-sudo for the current user; and
2. Cleaning it up using traps

Could solve this problem a bit better?

**Comment by ezzatron** [comment]
More info on brew invalidating the sudo timestamp: https://github.com/Homebrew/legacy-homebrew/issues/22865

**Comment by ezzatron** [comment]
Could well be "fixed" by now too. But testing it is kinda hard.

**Comment by jmalloc** [comment]
Thanks, dude.

Yeah I don't see any reference to `sudo` at all in here, yet I don't recall hitting a problem when I installed Mojave, which was my first scratch install in some time. Is it possible I just don't do anything that needs sudo? That seems unlikely 😕 

I'm going to be redoing this repo from scratch for Catalina with zsh, so it's probably worth trying to solve properly there.  I do recall having tried the "loop in a background process" method at some time in the past.

**Comment by jmalloc** [comment]
Ahh, and this is the "solution" I was thinking of when we last spoke:

https://github.com/jmalloc/dotfiles/commit/518b9b295aba60f6e10d03c7d0413f26681eaa0c#diff-a0f848942ce863cf53c0fa6cc684007dR4

It looks like this entire file is gone now, replaced with `install` at some point.

**Comment by jmalloc** [comment]
(That's from 2013)

**Comment by ezzatron** [comment]
Yeah okay. That probably worked well because `port` used to require `sudo` anyway, but `brew` doesn't like it.

The main point at which I find sudo is required during a fresh install is after `brew` has finished installing "normal" packages, and moves on to installing casks. It usually asks for a password the first time it installs a cask. But the first cask install can happen long into the install process.

I wonder if it could be alleviated by telling brew to install casks first somehow? Not sure if that's possible with `brew bundle`.

**Comment by jmalloc** [comment]
> I wonder if it could be alleviated by telling brew to install casks first somehow? Not sure if that's possible with `brew bundle`.

Hrm, possibly not.  Now that you mention it though, I think I may have skipped using `brew bundle` when I installed Mojave because at the time `mas` wasn't working.  So maybe I manually ran my brew installs separately or something.  I do install a few things with casks though, so I must have required sudo as well 🤷‍♂

**Comment by jmalloc** [comment]
Fixed on `catalina` branch (which is now the default).
