### ISSUE TITLE
Add support for High Sierra

### ISSUE THREAD

**Issue by parkertr** [jmalloc/dotfiles#8]
Some of these things are related to me downloading a zip and not via `git clone` so feel free to trim to a more succinct list.

I will update this with more specifics when I get a chance.

- bash-completions
- env python2 (could be related to bash completions
> env: python2: No such file or directory make[4]:
- `dirname "$0"`
> dirname: illegal option -- b
> usage: dirname path
* docker toolbox
> Error: Cask 'dockertoolbox' is unavailable: No Cask with this name exists. Did you mean “docker-toolbox”?

**Comment by parkertr** [comment]
Some of these things propagated into other things: eg, $DOTFILES_DIR wasn't populated.  $GITHUB_COM_TOKEN was empty etc.

So fixing the first issue may actually fix other issues.

**Comment by jmalloc** [comment]
What was the problem with `bash-completions`, any idea?

**Comment by parkertr** [comment]
Nope, but a heap of things aren't available through brew now - slack, chrome, docker-toolbox.

I really haven't gone through the list definitively.

**Comment by jmalloc** [comment]
I want to give [mas](https://github.com/mas-cli/mas) a try this time round.

**Comment by parkertr** [comment]
Is that so more things keep updated by themselves?

**Comment by jmalloc** [comment]
Mostly just for consistency, really. The bulk of the apps I install via casks have their own update process anyway, though I have had some issue with Slack updates in the past.

I think Atom and Chrome are the only apps I use regularly that *aren't* in the app store.

**Comment by jmalloc** [comment]
As an aside, also going to give [this prompt](https://github.com/arialdomartini/oh-my-git) a whirl, get rid of another chunk of custom stuff (this might be relevant to you @koden-km)

**Comment by parkertr** [comment]
Wow - that prompt looks pretty schmick.

**Comment by koden-km** [comment]
I will wait and see it in action. It looks a bit too noisy.

**Comment by jmalloc** [comment]
See `high-sierra` branch... I tried that prompt out but it was too much of a PITA - it needed specific fonts, etc.

**Comment by jmalloc** [comment]
Note, I haven't yet redone the `0.osx.bash` file from the old `setup` folder (the one that does all the osx defaults) -- I haven't seemed to be bothered by most of this stuff on my iMac, but I'll probably add a few back in over time.

@danhenke should publish his cutdown version so we can steal it.

**Comment by jmalloc** [comment]
Uh, also, if you guys are still using lastpass... this now uses 1Password, sorry!

**Comment by danhenke** [comment]
not sure theres much worth stealing, but got for it..

https://github.com/danhenke/osx

**Comment by danhenke** [comment]
I really should rename that to macOS now!

**Comment by jmalloc** [comment]
Everyone check out `Brewfile` ... OMFG so much more pleasant than what I was doing. That's what's worth stealing! :)

**Comment by jmalloc** [comment]
Merged to `master`.
